# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install requirements
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            . .venv/bin/activate
            flake8
            py.test -vsx tests/ --cov algorithms/ --no-cov-on-fail --junitxml=/tmp/test-results/junit.xml
            bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results          
